### ISSUE TITLE
any chance of a 2.13 build? 

### ISSUE THREAD

**Issue by danielbe1** [sake92/hepek#80]

**Comment by sake92** [comment]
Of course. 
I'll find time this week to do it.  
If you're in a hurry, send a PR maybe?  😛 

Out of curiosity, have you found any issues or something that could've been improved?

**Comment by danielbe1** [comment]
Not yet, admittedly I have only just begun using it to generate content for a personal project but have not run into any issue and everything looks pretty solid and easily expandable. Ill open the PR soon to help expedite the issue so I can shift up a gear on my site.

**Comment by sake92** [comment]
Getting weird Coursier error regarding caching on Travis: https://travis-ci.org/sake92/hepek/jobs/617623009  
I asked for help on Gitter, we'll see..

**Comment by sake92** [comment]
@danielbe1 0.5.0 is out! 😉
